# Generated by Django 5.2.6 on 2025-09-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aiquest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teachers_name', models.CharField(max_length=25)),
                ('course_name', models.CharField(max_length=25)),
                ('course_duration', models.IntegerField()),
                ('sit', models.IntegerField()),
            ],
        ),
    ]
